//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 01:58:19 PM EEST 
//


package org.exampleforlab3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.exampleforlab3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Laba3_QNAME = new QName("http://www.example.org/NewXMLSchema1", "laba3");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.exampleforlab3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link Polka }
     * 
     */
    public Polka createPolka() {
        return new Polka();
    }

    /**
     * Create an instance of {@link Laba3 }
     * 
     */
    public Laba3 createLaba3() {
        return new Laba3();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Laba3 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/NewXMLSchema1", name = "laba3")
    public JAXBElement<Laba3> createLaba3(Laba3 value) {
        return new JAXBElement<Laba3>(_Laba3_QNAME, Laba3 .class, null, value);
    }

}
