//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 01:58:19 PM EEST 
//


package org.exampleforlab3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Polka complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Polka">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nomer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="riad" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="book" type="{http://www.example.org/NewXMLSchema1}Book" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Polka", propOrder = {
    "nomer",
    "riad",
    "book"
})
public class Polka {

    @XmlElement(namespace = "http://www.example.org/NewXMLSchema1")
    protected int nomer;
    @XmlElement(namespace = "http://www.example.org/NewXMLSchema1")
    protected int riad;
    @XmlElement(namespace = "http://www.example.org/NewXMLSchema1", required = true)
    protected List<Book> book;

    /**
     * Gets the value of the nomer property.
     * 
     */
    public int getNomer() {
        return nomer;
    }

    /**
     * Sets the value of the nomer property.
     * 
     */
    public void setNomer(int value) {
        this.nomer = value;
    }

    /**
     * Gets the value of the riad property.
     * 
     */
    public int getRiad() {
        return riad;
    }

    /**
     * Sets the value of the riad property.
     * 
     */
    public void setRiad(int value) {
        this.riad = value;
    }

    /**
     * Gets the value of the book property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the book property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBook().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Book }
     * 
     * 
     */
    public List<Book> getBook() {
        if (book == null) {
            book = new ArrayList<Book>();
        }
        return this.book;
    }

}
